#!/bin/sh
# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0
set -eu

CHROOT=${CHROOT:-"/mnt/rootfs"}

n=0
max=2

until [ $n -gt $max ]; do
    set +e
    (
      microdnf install -y --setopt install_weak_deps=0 --nodocs --noplugins --config=/etc/dnf/dnf.conf --setopt=cachedir="$CHROOT/var/cache/yum" --setopt=reposdir=/etc/yum.repos.d --setopt=varsdir=/etc/dnf --releasever=9 --installroot $CHROOT "$@"
    )
    CODE=$?
    set -e
    if [ $CODE -eq 0 ]; then
        break
    fi
    if [ $n -eq $max ]; then
        exit $CODE
    fi
    echo "microdnf failed, retrying"
    n=$(($n + 1))
done
